# -*- coding: utf-8 -*-
"""data_cleaning 2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1TDHKGHSSqsO2pLvDQUIH0IVvjjHelSqj
"""

import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import pandas as pd
from google.colab import files

rework = pd.read_excel('/content/Rework Statistics - WebReports 1.xlsx', header= 1)

print("rework's shape : ", rework.shape)

df=pd.DataFrame(rework)
print(df)

df = df.drop(columns=['QMUserName','QMUserScanCode', 'Location_Dest','OperatorComment'])

df.info()

df.isnull().sum()

df.columns[df.isna().all()]

df[df.duplicated()]

df.describe(include='all')

df.columns = (
    df.columns
      .str.strip()
      .str.upper()
      .str.replace(" ", "_", regex=False)
      .str.replace("-", "_", regex=False)
)

for col in df.select_dtypes(include='object').columns:

    df[col] = (
        df[col]
        .astype(str)
        .str.strip()
        .str.upper()
    )

print(df)

df.to_excel("Table1.xlsx", index=False)

print("\nTable nettoyée exportée avec succès.")

rework2 = pd.read_excel('/content/Rework Statistics - WebReports 2.xlsx', header= 1)

# dataset's shape (n_obervations and n_features)
print("rework's shape : ", rework2.shape)

df2=pd.DataFrame(rework2)
print(df2)

df2 = df2.drop(columns=['WorkTime','Comment'])

df2.info()

df2.isnull().sum()

df2.columns[df2.isna().all()]

df2[df2.duplicated()]

df2.columns = (
    df2.columns
      .str.strip()
      .str.upper()
      .str.replace(" ", "_", regex=False)
      .str.replace("-", "_", regex=False)
)

for col in df2.select_dtypes(include='object').columns:

    df2[col] = (
        df2[col]
        .astype(str)
        .str.strip()
        .str.upper()
    )

print(df2)

df2.to_excel("Table2.xlsx", index=False)

print("\nTable nettoyée exportée avec succès.")

print(df.columns.tolist())
print(df2.columns.tolist())

master = pd.merge(
    df.drop(columns=['MACHINE']),
    df2[['ORDERNUMBER', 'SUBORDERINDEX', 'MACHINE', 'ERRORCODE', 'ERRORTEXT']],
    on=['ORDERNUMBER', 'SUBORDERINDEX'],
    how='left'
)

print(master)

master.isnull().sum()

missing=master.isna().sum()
print(missing)

master.to_excel("fusion.xlsx", index=False)

print("\nTable nettoyée exportée avec succès.")