# -*- coding: utf-8 -*-
"""data_cleaning 1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1xxEShbAS18gUrQqIn9HJC70WfeSLXQa3
"""

import pandas as pd
import numpy as np
df = pd.read_excel(
    r"C:\Users\manar\Downloads\Rework Statistics - WebReports 3.xlsx",
    header=1
)

print(f"Lignes : {df.shape[0]} | Colonnes : {df.shape[1]}")
df.head()

print("=== Types des colonnes ===")
print(df.dtypes)
print()
print("=== Valeurs nulles ===")
print(df.isnull().sum())
print()
print("=== Valeurs uniques par colonne ===")
for col in df.columns:
    print(f"  {col}: {df[col].nunique()} valeurs uniques")

constant_cols = [col for col in df.columns if df[col].nunique(dropna=False) <= 1]
print("Colonnes constantes détectées :", constant_cols)
df = df.drop(columns=constant_cols)

cols_to_drop = [c for c in ["OperatorScanCode", "UserName"] if c in df.columns]
df = df.drop(columns=cols_to_drop)
print("Colonnes anonymes supprimées :", cols_to_drop)

print(f"\nColonnes restantes ({df.shape[1]}) :", list(df.columns))

for col in ["CreateTime", "StartTime", "CompleteTime"]:
    df[col] = pd.to_datetime(df[col], dayfirst=True, errors="coerce")

df["WorkTime"] = pd.to_numeric(df["WorkTime"], errors="coerce")

print("Types après conversion :")
print(df[["CreateTime", "StartTime", "CompleteTime", "WorkTime"]].dtypes)
print()
print("Nulls introduits par la conversion :")
print(df[["CreateTime", "StartTime", "CompleteTime", "WorkTime"]].isnull().sum())

Q1 = df["WorkTime"].quantile(0.25)
Q3 = df["WorkTime"].quantile(0.75)
IQR = Q3 - Q1
borne_sup = Q3 + 3 * IQR

print(f"Q1={Q1:.2f} | Q3={Q3:.2f} | IQR={IQR:.2f}")
print(f"Borne supérieure (Q3 + 3×IQR) = {borne_sup:.2f} minutes")
print(f"Outliers détectés : {(df['WorkTime'] > borne_sup).sum()} lignes")

df["WorkTime_outlier"] = df["WorkTime"] > borne_sup
print(f"\nColonne 'WorkTime_outlier' ajoutée (True = valeur suspecte)")
print(df[df["WorkTime_outlier"]][["Machine", "Route", "WorkTime", "CreateTime"]].head(5))

df["Heure"]        = df["CreateTime"].dt.hour
df["JourSemaine"]  = df["CreateTime"].dt.dayofweek
df["NomJour"]      = df["CreateTime"].dt.day_name(locale="fr_FR")
df["Semaine"]      = df["CreateTime"].dt.isocalendar().week.astype(int)
df["Mois"]         = df["CreateTime"].dt.month
df["Date"]         = df["CreateTime"].dt.date

print("Variables temporelles créées :")
print(df[["CreateTime", "Heure", "JourSemaine", "NomJour", "Semaine", "Mois", "Date"]].head(5))

output_path = r"C:\Users\manar\Downloads\WebReports3_clean.csv"
df.to_csv(output_path, index=False, encoding="utf-8-sig")
print(f"CSV exporté : {output_path}")

output_excel = r"C:\Users\manar\Downloads\WebReports3_clean.xlsx"
df.to_excel(output_excel, index=False)
print(f"Excel exporté : {output_excel}")

print(f"\nFichier prêt : {df.shape[0]} lignes × {df.shape[1]} colonnes")