# -*- coding: utf-8 -*-
"""K-means.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1zipxhmvyJgok4xUxy_7FUrptu9pEmujc
"""

import pandas as pd
from sklearn.preprocessing import LabelEncoder, StandardScaler
from sklearn.cluster import KMeans
from sklearn.metrics import silhouette_score
import warnings
warnings.filterwarnings('ignore')
df_wr = pd.read_excel('/content/dataset_sans_doublons.xlsx')
df_fw = pd.read_excel('/content/fusion.xlsx')

df = pd.merge(
    df_fw[['ORDERNUMBER','SUBORDERINDEX','MACHINE','ROUTE','ERRORCODE','CREATETIME']],
    df_wr[['OrderNumber','SubOrderIndex','WorkTime','StartTime']],
    left_on=['ORDERNUMBER','SUBORDERINDEX'],
    right_on=['OrderNumber','SubOrderIndex'],
    how='left'
)

df['StartTime']  = pd.to_datetime(df['StartTime'],  format='%d-%m-%Y %H:%M:%S', errors='coerce')
df['CREATETIME'] = pd.to_datetime(df['CREATETIME'], format='%d-%m-%Y %H:%M:%S', errors='coerce')
df['Timestamp']  = df['StartTime'].fillna(df['CREATETIME'])
df['Heure']       = df['Timestamp'].dt.hour
df['JourSemaine'] = df['Timestamp'].dt.dayofweek

df_km = df[['ORDERNUMBER','SUBORDERINDEX','MACHINE','ROUTE',
            'ERRORCODE','Heure','JourSemaine','WorkTime']].copy()

df_km.dropna(subset=['MACHINE','ROUTE','ERRORCODE',
                     'Heure','JourSemaine','WorkTime'], inplace=True)

df_km['WorkTime'] = df_km['WorkTime'].clip(upper=df_km['WorkTime'].quantile(0.99))

le_machine = LabelEncoder()
le_route   = LabelEncoder()
le_error   = LabelEncoder()

df_km['Machine_enc']   = le_machine.fit_transform(df_km['MACHINE'])
df_km['Route_enc']     = le_route.fit_transform(df_km['ROUTE'])
df_km['ErrorCode_enc'] = le_error.fit_transform(df_km['ERRORCODE'].astype(str))


features = ['Machine_enc', 'Route_enc', 'ErrorCode_enc',
            'Heure', 'JourSemaine', 'WorkTime']

X_scaled = StandardScaler().fit_transform(df_km[features].values)


km = KMeans(n_clusters=3, init='k-means++', n_init=50, max_iter=500, random_state=42)
df_km['Cluster'] = km.fit_predict(X_scaled)


score = silhouette_score(X_scaled, df_km['Cluster'])
print(f"Score silhouette : {score:.4f}")


for c in sorted(df_km['Cluster'].unique()):
    sub = df_km[df_km['Cluster'] == c]
    print(f"\n--- Cluster {c} ({len(sub)} reworks) ---")
    print(f"  WorkTime moyen : {sub['WorkTime'].mean():.2f} min")
    print(f"  Heure moyenne  : {sub['Heure'].mean():.1f}h")
    print(f"  Top MACHINE    : {sub['MACHINE'].value_counts().index[0]}")
    print(f"  Top ERRORCODE  : {sub['ERRORCODE'].value_counts().index[0]}")
    print(f"  Top ROUTE      : {sub['ROUTE'].value_counts().index[0]}")


df_km[['ORDERNUMBER','SUBORDERINDEX','MACHINE','ROUTE',
       'ERRORCODE','Heure','JourSemaine','WorkTime','Cluster']]\
    .to_excel('kmeans_clusters.xlsx', index=False)

print(f"\n Export OK — {len(df_km)} lignes")

import pandas as pd
from sklearn.preprocessing import LabelEncoder, StandardScaler
from sklearn.cluster import KMeans
from sklearn.metrics import silhouette_score
import warnings
warnings.filterwarnings('ignore')


df_wr = pd.read_excel('/content/dataset_sans_doublons.xlsx')
df_fw = pd.read_excel('/content/fusion.xlsx')


df = pd.merge(
    df_fw[['ORDERNUMBER','SUBORDERINDEX','MACHINE','ROUTE','ERRORCODE','CREATETIME']],
    df_wr[['OrderNumber','SubOrderIndex','WorkTime','StartTime']],
    left_on=['ORDERNUMBER','SUBORDERINDEX'],
    right_on=['OrderNumber','SubOrderIndex'],
    how='left'
)


df['StartTime']  = pd.to_datetime(df['StartTime'],  format='%d-%m-%Y %H:%M:%S', errors='coerce')
df['CREATETIME'] = pd.to_datetime(df['CREATETIME'], format='%d-%m-%Y %H:%M:%S', errors='coerce')
df['Timestamp']  = df['StartTime'].fillna(df['CREATETIME'])
df['Heure']       = df['Timestamp'].dt.hour
df['JourSemaine'] = df['Timestamp'].dt.dayofweek


df_km = df[['ORDERNUMBER','SUBORDERINDEX','MACHINE','ROUTE',
            'ERRORCODE','Heure','JourSemaine','WorkTime']].copy()
df_km.dropna(subset=['MACHINE','ROUTE','ERRORCODE',
                     'Heure','JourSemaine','WorkTime'], inplace=True)
df_km['WorkTime'] = df_km['WorkTime'].clip(upper=df_km['WorkTime'].quantile(0.99))


le_machine = LabelEncoder()
le_route   = LabelEncoder()
le_error   = LabelEncoder()
df_km['Machine_enc']   = le_machine.fit_transform(df_km['MACHINE'])
df_km['Route_enc']     = le_route.fit_transform(df_km['ROUTE'])
df_km['ErrorCode_enc'] = le_error.fit_transform(df_km['ERRORCODE'].astype(str))


features = ['Machine_enc','Route_enc','ErrorCode_enc',
            'Heure','JourSemaine','WorkTime']
X_scaled = StandardScaler().fit_transform(df_km[features].values)


print("Analyse de tous les K possibles :")
print(f"{'K':>3}  {'Silhouette':>10}  {'Inertie':>12}  {'Clusters équilibrés':>20}")
print("-" * 55)

resultats = []
for k in range(2, 11):
    km_test = KMeans(n_clusters=k, init='k-means++',
                     n_init=50, max_iter=500, random_state=42)
    labels   = km_test.fit_predict(X_scaled)
    sil      = silhouette_score(X_scaled, labels)
    inertia  = km_test.inertia_


    counts      = pd.Series(labels).value_counts()
    min_pct     = counts.min() / len(labels) * 100
    equilibre   = "Oui" if min_pct >= 1.0 else f"Non (min={min_pct:.1f}%)"

    resultats.append({
        'K': k, 'silhouette': sil,
        'inertia': inertia, 'equilibre': equilibre,
        'min_pct': min_pct, 'labels': labels
    })
    print(f"{k:>3}  {sil:>10.4f}  {inertia:>12.1f}  {equilibre:>20}")


candidats = [r for r in resultats
             if r['min_pct'] >= 1.0
             and not (r['K'] == 2 and r['silhouette'] > 0.5)]

if candidats:
    meilleur  = max(candidats, key=lambda x: x['silhouette'])
else:

    meilleur  = next(r for r in resultats if r['K'] == 3)

best_k      = meilleur['K']
best_score  = meilleur['silhouette']
best_labels = meilleur['labels']

print(f"\n{'='*55}")
print(f"K retenu automatiquement : K={best_k}")
print(f"   Score silhouette         : {best_score:.4f}")
print(f"{'='*55}")


df_km['Cluster'] = best_labels


print(f"\nProfil des {best_k} clusters :")
for c in sorted(df_km['Cluster'].unique()):
    sub = df_km[df_km['Cluster'] == c]
    print(f"\n  Cluster {c} — {len(sub)} reworks ({len(sub)/len(df_km)*100:.1f}%)")
    print(f"    WorkTime moyen : {sub['WorkTime'].mean():.2f} min")
    print(f"    Heure moyenne  : {sub['Heure'].mean():.1f}h")
    print(f"    Top MACHINE    : {sub['MACHINE'].value_counts().index[0]}")
    print(f"    Top ERRORCODE  : {sub['ERRORCODE'].value_counts().index[0]}")
    print(f"    Top ROUTE      : {sub['ROUTE'].value_counts().index[0]}")


df_km[['ORDERNUMBER','SUBORDERINDEX','MACHINE','ROUTE',
       'ERRORCODE','Heure','JourSemaine','WorkTime','Cluster']]\
    .to_excel('kmeans_clusters.xlsx', index=False)

print(f"\n Export OK — {len(df_km)} lignes — K={best_k} clusters")