# -*- coding: utf-8 -*-
"""Random_Forest.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/18rwiwuVsDjWcCYQApRmimX2HYqcXqEf5
"""

import pandas as pd
import numpy as np
t1 = pd.read_excel("/content/dataset_modifie.xlsx")
t2 = pd.read_excel("/content/fusion.xlsx")

print("Table1:", t1.shape)
print("Table2:"   , t2.shape)

t1.columns = t1.columns.str.upper().str.strip()
t2.columns = t2.columns.str.upper().str.strip()

for col in ["ORDERNUMBER", "SUBORDERINDEX"]:
    t1[col] = t1[col].astype(str).str.strip()
    t2[col] = t2[col].astype(str).str.strip()

print("Vrais doublons table2 :", t2.duplicated().sum())
print("Vrais doublons table1 :", t1.duplicated().sum())

print(t1[t1.duplicated(keep=False)].sort_values(list(t1.columns)).head(6))

t2_dedup = t2.drop_duplicates().reset_index(drop=True)
print("Table2 :", t2.shape[0], "→", t2_dedup.shape[0], "lignes")
t1_dedup = (
    t1.drop_duplicates()
    .sort_values("WORKTIME", ascending=False)
    .drop_duplicates(subset=["ORDERNUMBER", "SUBORDERINDEX"], keep="first")
    .reset_index(drop=True)
)
print("Table1 :", t1.shape[0], "→", t1_dedup.shape[0], "lignes")

df = pd.merge(
    t2_dedup,
    t1_dedup,
    on=["ORDERNUMBER", "SUBORDERINDEX"],
    how="left",
    suffixes=("_rew", "_prod")
)

print("Shape après fusion :", df.shape)

df["MACHINE"]      = df["MACHINE_prod"]
df["MACHINE_REW"] = df["MACHINE_rew"]
df["ROUTE"]     = df["ROUTE_prod"]
df["ROUTESTEP"] = df["ROUTESTEP_prod"]
df["NODENAME"]  = df["NODENAME_rew"]

cols_to_drop = [c for c in df.columns if c.endswith(("_rew", "_prod"))]
df.drop(columns=cols_to_drop, inplace=True)

print("Shape finale        :", df.shape)

match_rate = df["STARTTIME"].notna().mean() * 100
print(f"Taux de correspondance : {match_rate:.1f}%")

df["CREATETIME"] = pd.to_datetime(df["CREATETIME"], dayfirst=True)

df["HOUR"]       = df["CREATETIME"].dt.hour
df["DAYOFWEEK"]  = df["CREATETIME"].dt.dayofweek
df["WEEK_ISO"]   = df["CREATETIME"].dt.isocalendar().week.astype(int)

df = df.sort_values("CREATETIME").reset_index(drop=True)

df["DATE"] = df["CREATETIME"].dt.date

def rolling_rework_count(df, days):
    counts = []
    for idx, row in df.iterrows():
        cutoff = row["CREATETIME"] - pd.Timedelta(days=days)
        mask = (
            (df["MACHINE"] == row["MACHINE"]) &
            (df["CREATETIME"] >= cutoff) &
            (df["CREATETIME"] < row["CREATETIME"])
        )
        counts.append(mask.sum())
    return counts

df["REWORK_7D"]  = rolling_rework_count(df, 7)
df["REWORK_14D"] = rolling_rework_count(df, 14)

from sklearn.preprocessing import LabelEncoder
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import GridSearchCV
from sklearn.metrics import f1_score, classification_report

combo_freq = (
    df.groupby(["MACHINE", "ROUTE", "HOUR"])
    .size()
    .reset_index(name="COMBO_COUNT")
)
df = df.merge(combo_freq, on=["MACHINE", "ROUTE", "HOUR"], how="left")

threshold = df["COMBO_COUNT"].quantile(0.75)
df["TARGET"] = (df["COMBO_COUNT"] >= threshold).astype(int)

print("Distribution cible :")
print(df["TARGET"].value_counts(normalize=True).round(3))

for col in ["MACHINE", "ROUTE", "ROUTESTEP", "ERRORCODE", "NODENAME"]:
    df[col + "_ENC"] = LabelEncoder().fit_transform(df[col].astype(str))

print("Colonnes encodées :", [c for c in df.columns if c.endswith("_ENC")])

FEATURES = [
    "ROUTE_ENC", "ROUTESTEP_ENC", "ERRORCODE_ENC",
    "HOUR", "DAYOFWEEK", "WEEK_ISO",
    "REWORK_7D", "REWORK_14D"
]

df = df.sort_values("CREATETIME").reset_index(drop=True)
split_idx = int(len(df) * 0.80)
train = df.iloc[:split_idx]
test  = df.iloc[split_idx:]

X_train, y_train = train[FEATURES], train["TARGET"]
X_test,  y_test  = test[FEATURES],  test["TARGET"]

print(f"Train : {len(train)} lignes | Test : {len(test)} lignes")
print(f"Taux critiques train : {y_train.mean():.2%}")
print(f"Taux critiques test  : {y_test.mean():.2%}")
print(f"Shape X_train : {X_train.shape} | Shape X_test : {X_test.shape}")

param_grid = { "n_estimators":     [100, 200], "max_depth":        [None, 10, 20], "min_samples_leaf": [1, 5]}
rf = RandomForestClassifier(random_state=42, class_weight="balanced")
gs = GridSearchCV(rf, param_grid, cv=3, scoring="f1", n_jobs=-1)
gs.fit(X_train, y_train)

best_model = gs.best_estimator_
print("Meilleurs paramètres :", gs.best_params_)

y_proba = best_model.predict_proba(X_test)[:, 1]

thresholds = np.arange(0.3, 0.8, 0.05)
results = []
for t in thresholds:
    y_pred_t = (y_proba >= t).astype(int)
    f1 = f1_score(y_test, y_pred_t, zero_division=0)
    results.append((round(t, 2), round(f1, 3)))

results_df = pd.DataFrame(results, columns=["Seuil", "F1"])
print(results_df)

best_threshold = results_df.loc[results_df["F1"].idxmax(), "Seuil"]
print(f"\nMeilleur seuil retenu : {best_threshold}")

y_pred_final = (y_proba >= best_threshold).astype(int)

print(f"F1-Score final : {f1_score(y_test, y_pred_final):.3f}")
print(classification_report(y_test, y_pred_final))

feat_imp = pd.Series(
    best_model.feature_importances_,
    index=FEATURES
).sort_values(ascending=False)
print("Importances des features :")
print(feat_imp)

df["CRITICALITY_PROBA"] = best_model.predict_proba(df[FEATURES])[:, 1]
df["CRITICALITY_SCORE"] = (df["CRITICALITY_PROBA"] * 100).round(1)
df["CRITICALITY_LABEL"] = pd.cut(
    df["CRITICALITY_SCORE"],
    bins=[0, 40, 70, 100],
    labels=["Faible", "Moyen", "Élevé"]
)

result = (
    df.groupby(["MACHINE", "ROUTE", "HOUR"])
    .agg(
        SCORE_MOYEN=("CRITICALITY_SCORE", "mean"),
        NB_REWORKS=("ORDERNUMBER", "count")
    )
    .reset_index()
)
result["SCORE_MOYEN"] = result["SCORE_MOYEN"].round(1)
result["CRITICALITY_LABEL"] = pd.cut(
    result["SCORE_MOYEN"],
    bins=[0, 40, 70, 100],
    labels=["Faible", "Moyen", "Élevé"]
)


print("Shape :", result.shape)
result.to_csv(
    '/content/criticality_scores.csv',
    index=False, sep=";"
)

print("Distribution CRITICALITY_SCORE brut :")
print(df["CRITICALITY_SCORE"].describe())
print(df["CRITICALITY_SCORE"].value_counts(bins=5).sort_index())

print("Distribution labels :")
print(result["CRITICALITY_LABEL"].value_counts())

print("\nTop 10 combinaisons critiques :")
print(result.sort_values("SCORE_MOYEN", ascending=False).head(10))

print("\nNombre de combinaisons :", len(result))

t2_dedup.to_excel("t2_dedup.xlsx", index=False)